root_node: 'Is this company on the black list?'

additional_context:
  Resume: Sullivan_Crouse_Resume.pdf
  JobTitles: job_titles.txt
  BlackList: black_list.txt

Agent_questions:

  'Is this company on the black list?':
    function: check_text_list
    additional_context:
      BlackList: True
    children:
     'No': 'Does the posting contain one of the job titles?'
     
  'Does the posting contain one of the job titles?':
    function: check_text_list
    additional_context:
      JobTitles: True
    children:
     'No': 'Does the description relate to one of the job titles?'
     'Yes': 'Is this posting legitimate?'

  'Does the description relate to one of the job titles?':
    function: query_llm
    prompt: title_matching
    return_payload:
      response: '\[Response\]\s*(.*?)\s*\[EndResponse\]'
      explanation: '\[Explanation\]\s*(.*?)\s*\[EndExplanation\]'
    children:
     'Yes': 'Is this posting legitimate?'
     'Unsure': 'Is this posting legitimate?'
        
  'Is this posting legitimate?':
     function: query_llm
     prompt: job_legitimacy
     return_payload:
       response: '\[Response\]\s*(.*?)\s*\[EndResponse\]'
       explanation: '\[Explanation\]\s*(.*?)\s*\[EndExplanation\]'
     children:
      'Yes': 'Are there any red flags present?'
      'Unsure': 'Are there any red flags present?'
    
  'Are there any red flags present?':
    function: query_llm
    prompt: red_flags
    return_payload:
      response: '\[Response\]\s*(.*?)\s*\[EndResponse\]'
      explanation: '\[Explanation\]\s*(.*?)\s*\[EndExplanation\]'
    children:
     'No': 'Is there a salary?'
     'Unsure': 'Is there a salary?'

  'Is there a salary?':
    function: query_llm
    prompt: salary_expectations
    return_payload:
      response: '\[Response\]\s*(.*?)\s*\[EndResponse\]'
      explanation: '\[Explanation\]\s*(.*?)\s*\[EndExplanation\]'
    children:
      Continue: 'How many years of required experience?'
  
  'How many years of required experience?':
    function: query_llm
    prompt_id: years_experience
    return_payload:
      response: '\[Response\]\s*(.*?)\s*\[EndResponse\]'
      explanation: '\[Explanation\]\s*(.*?)\s*\[EndExplanation\]'
    children:
      Continue: 'Is the required skillset present?'
        
  'Is the required skillset present?':
     function: query_llm
     prompt: skillset
     additional_context:
       Resume: '[Resume]{}[EndResume]'
     return_payload:
       response: '\[Response\]\s*(.*?)\s*\[EndResponse\]'
       explanation: '\[Explanation\]\s*(.*?)\s*\[EndExplanation\]'