LinkedInScraper:
  LandingPages:
    - https://www.linkedin.com/jobs/search/?currentJobId=4165605159&distance=25&f_TPR=r86400&geoId=102264677&keywords=data%20scientist&origin=JOB_SEARCH_PAGE_JOB_FILTER&refresh=true
    - https://www.linkedin.com/jobs/search/?currentJobId=4165605159&distance=25&f_TPR=r86400&geoId=102264677&keywords=data%20analyst&origin=JOB_SEARCH_PAGE_KEYWORD_AUTOCOMPLETE&refresh=true
    - https://www.linkedin.com/jobs/search/?currentJobId=4236792571&distance=25&f_TPR=r86400&geoId=102264677&keywords=data%20engineer&origin=JOB_SEARCH_PAGE_KEYWORD_AUTOCOMPLETE&refresh=true
    - https://www.linkedin.com/jobs/search/?currentJobId=4220237121&distance=25&f_TPR=r86400&geoId=102264677&keywords=machine%20learning%20engineer&origin=JOB_SEARCH_PAGE_KEYWORD_AUTOCOMPLETE&refresh=true
