scraper_config:
  classes:
    LinkedInScraper:
      LandingPages:
        - https://www.linkedin.com/jobs/search/?f_TPR=r86400&f_VJ=true&f_WT=2&keywords=data%20scientist&origin=JOB_SEARCH_PAGE_LOCATION_SUGGESTION&refresh=true&sortBy=R
        - https://www.linkedin.com/jobs/search/?f_TPR=r86400&f_VJ=true&f_WT=2&geoId=103644278&keywords=data%20analyst&origin=JOB_SEARCH_PAGE_SEARCH_BUTTON&refresh=true&sortBy=R
        - https://www.linkedin.com/jobs/search/?f_TPR=r86400&f_VJ=true&f_WT=2%2C1%2C3&geoId=102264677&keywords=data%20analyst&origin=JOB_SEARCH_PAGE_JOB_FILTER&refresh=true&sortBy=R
        - https://www.linkedin.com/jobs/search/?f_TPR=r86400&f_VJ=true&f_WT=1%2C2%2C3&geoId=102264677&keywords=data%20scientist&origin=JOB_SEARCH_PAGE_JOB_FILTER&refresh=true&sortBy=R
        - https://www.linkedin.com/jobs/search/?f_TPR=r86400&f_VJ=true&f_WT=2%2C1%2C3&geoId=102264677&keywords=machine%20learning%20engineer&origin=JOB_SEARCH_PAGE_JOB_FILTER&refresh=true&sortBy=R
        - https://www.linkedin.com/jobs/search/?f_TPR=r86400&f_VJ=true&f_WT=2&keywords=machine%20learning%20engineer&origin=JOB_SEARCH_PAGE_LOCATION_AUTOCOMPLETE&refresh=true&sortBy=R
        - https://www.linkedin.com/jobs/search/?f_TPR=r86400&f_VJ=true&f_WT=2&geoId=103644278&keywords=software%20engineer&origin=JOB_SEARCH_PAGE_SEARCH_BUTTON&refresh=true&sortBy=R
        - https://www.linkedin.com/jobs/search/?f_TPR=r86400&f_VJ=true&f_WT=1%2C2%2C3&geoId=102264677&keywords=software%20engineer&origin=JOB_SEARCH_PAGE_JOB_FILTER&refresh=true&sortBy=R



functions:
  run_scrapers:
    - config
    - db_handler
  process_unprocessed_jobs:
    - agent
    - db_handler


schedule:
  0:
    - run_scrapers
    - process_unprocessed_jobs
  10:
    - run_scrapers
    - process_unprocessed_jobs
  20:
    - run_scrapers
    - process_unprocessed_jobs
  30:
    - run_scrapers
    - process_unprocessed_jobs
  40:
    - run_scrapers
    - process_unprocessed_jobs
  50:
    - run_scrapers
    - process_unprocessed_jobs
